export const metadata = {
    title: 'پارسا',
    // description: 'Generated by create next app',
}
import  { use } from "react"
import Header from "./homeComponents/Header";
import Aside from "./homeComponents/Aside";
import Introduction from "./homeComponents/Introduction";
import Questions from "./homeComponents/Questions";
// import OurTeam from "./homeComponents/OurTeam";
import Footer from "./homeComponents/Footer";
import Error from "./error/Error";
import { getLastQuestions, getCategories } from "../dataService/homeData";



async function getQuestionsData() {
    try{
        const resposne = await getLastQuestions();
        return resposne.data;
    }
    catch(err) {
        console.log(err);
        return null;
    }
}

async function getCategoriesData(){
    const responseData = await getCategories();
    return responseData.data;
}

export default function Home() {
    
    const serverData = use(getQuestionsData())

    return (
        <>
            <main className="mainContentContainer">
                <Header />
                <div className="home-questionContainer">
                    {
                        serverData ? 
                        <Questions data={serverData.data}/>
                        :
                        <Error/>
                    }
                    <aside className="aside">
                        <Aside/>
                    </aside>
                </div>
                <Introduction />
                {/* <OurTeam /> */}
            </main>
            <Footer/>
        </>
    )
}
