export const metadata = {
    title: 'پارسا',
    // description: 'Generated by create next app',
}

import  { use } from "react"
import Header from "./homeComponents/Header";
import Aside from "./homeComponents/Aside";
import Introduction from "./homeComponents/Introduction";
import Questions from "./homeComponents/Questions";
// import OurTeam from "./homeComponents/OurTeam";
import Footer from "./homeComponents/Footer";
import Error from "./error/Error";
import { getLastQuestions, getCategories } from "../../dataService/homeData";

async function getQuestionsData(locale) {
    try{
        const resposne = await getLastQuestions(locale);
        return resposne.data;
    }
    catch(err) {
        console.log(err);
        return null;
    }
}

async function getCategoriesData(){
    try{
        const responseData = await getCategories(1);
        return responseData.data;
    }
    catch(err) {
        console.log(err);
        return null;
    }
    
}

export default function Home({ params : { locale }}) {
    const serverData = use(getQuestionsData(locale));
    const categories = ( use(getCategoriesData()) );

    return (
        <>
            <main className="mainContentContainer">
                <Header lang={locale} />
                <div className="home-questionContainer">
                    {
                        serverData ? 
                        <Questions data={serverData.data}/>
                        :
                        <Error/>
                    }
                    <aside className="aside">
                        {
                            categories ? 
                            <Aside data={categories.data}/> : <></>
                        }
                    </aside>
                </div>
                <Introduction />
                {/* <OurTeam /> */}
            </main>
            <Footer/>
        </>
    )
}
